# Generated by Django 4.2.21 on 2025-05-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='default-icon.png', max_length=100),
        ),
    ]
