# Generated by Django 4.2.21 on 2025-05-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_badge_icon_badge_image_alter_userbadge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_hours_detoxed',
            field=models.FloatField(default=0.0),
        ),
    ]
