# Generated by Django 4.2.20 on 2025-05-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile_total_hours_detoxed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_hours_detoxed',
            new_name='total_minutes_detoxed',
        ),
    ]
