# Generated by Django 4.2.20 on 2025-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_total_hours_detoxed_userprofile_total_minutes_detoxed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_detox_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
