# Generated by Django 4.2.20 on 2025-05-09 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_userprofile_last_detox_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
        migrations.AddField(
            model_name='badge',
            name='awarded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
